AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Federated Authentication Add-on for DCC API

Parameters:
  UserPoolId:
    Type: String
    Description: Existing Cognito User Pool ID to add federated providers to
  
  GoogleClientId:
    Type: String
    Description: Google OAuth 2.0 Client ID for social login
  
  GoogleClientSecret:
    Type: String
    NoEcho: true
    Description: Google OAuth 2.0 Client Secret for social login
  
  AppleServicesId:
    Type: String
    Description: Apple Services ID for Sign in with Apple
    Default: com.anystupididea.quoteme.signin
  
  AppleTeamId:
    Type: String
    Description: Apple Developer Team ID
  
  AppleKeyId:
    Type: String
    Description: Apple Sign in with Apple Key ID
  
  ApplePrivateKey:
    Type: String
    NoEcho: true
    Description: Apple Sign in with Apple Private Key (p8 file content)

Resources:
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPoolId
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: 'openid email profile'
      AttributeMapping:
        email: email
        given_name: given_name
        family_name: family_name

  AppleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPoolId
      ProviderName: SignInWithApple
      ProviderType: SignInWithApple
      ProviderDetails:
        client_id: !Ref AppleServicesId
        team_id: !Ref AppleTeamId
        key_id: !Ref AppleKeyId
        private_key: !Ref ApplePrivateKey
        authorize_scopes: 'openid email name'
      AttributeMapping:
        email: email
        given_name: given_name
        family_name: family_name

Outputs:
  GoogleProviderName:
    Description: Google Identity Provider Name
    Value: Google
  
  AppleProviderName:
    Description: Apple Identity Provider Name
    Value: SignInWithApple