AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quote Me API - Minimal deployment for basic quote functionality

Parameters:
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API key for tag generation

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        QUOTES_TABLE: !Ref QuotesTable
        TAGS_TABLE: !Ref TagsTable
        OPENAI_API_KEY: !Ref OpenAIApiKey
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # DynamoDB Tables
  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: quote-me-quotes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: author
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: AuthorIndex
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: quote-me-tags
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tag
          AttributeType: S
      KeySchema:
        - AttributeName: tag
          KeyType: HASH

  # API Gateway
  QuoteMeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: quote-me-api
      StageName: prod
      Auth:
        ApiKeyRequired: true

  # Lambda Functions
  QuoteHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: quote-me-quote-handler
      CodeUri: lambda/
      Handler: quote_handler.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuotesTable
        - DynamoDBReadPolicy:
            TableName: !Ref TagsTable
      Events:
        GetRandomQuote:
          Type: Api
          Properties:
            RestApiId: !Ref QuoteMeApi
            Path: /quote
            Method: GET
            Auth:
              ApiKeyRequired: true
        GetQuoteById:
          Type: Api
          Properties:
            RestApiId: !Ref QuoteMeApi
            Path: /quote/{id}
            Method: GET
            Auth:
              ApiKeyRequired: true

  TagsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: quote-me-tags-handler
      CodeUri: lambda/
      Handler: tags_handler.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TagsTable
      Events:
        GetTags:
          Type: Api
          Properties:
            RestApiId: !Ref QuoteMeApi
            Path: /tags
            Method: GET
            Auth:
              ApiKeyRequired: true

  OptionsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: quote-me-options-handler
      CodeUri: lambda/
      Handler: options_handler.lambda_handler
      Events:
        OptionsQuote:
          Type: Api
          Properties:
            RestApiId: !Ref QuoteMeApi
            Path: /quote
            Method: OPTIONS
            Auth:
              ApiKeyRequired: false
        OptionsQuoteById:
          Type: Api
          Properties:
            RestApiId: !Ref QuoteMeApi
            Path: /quote/{id}
            Method: OPTIONS
            Auth:
              ApiKeyRequired: false
        OptionsTags:
          Type: Api
          Properties:
            RestApiId: !Ref QuoteMeApi
            Path: /tags
            Method: OPTIONS
            Auth:
              ApiKeyRequired: false

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${QuoteMeApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  
  QuotesTableName:
    Description: DynamoDB Quotes Table Name
    Value: !Ref QuotesTable
  
  TagsTableName:
    Description: DynamoDB Tags Table Name
    Value: !Ref TagsTable