AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DCC Infrastructure - S3, DynamoDB, SQS

Resources:
  # S3 Bucket for Quote Images
  QuoteImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-quote-images"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3600

  # S3 Bucket Policy for Public Read Access
  QuoteImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: QuoteImagesBucket
    Properties:
      Bucket: !Ref QuoteImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${QuoteImagesBucket}/*"

  # S3 Bucket for Exports
  ExportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-exports"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter7Days
            Status: Enabled
            ExpirationInDays: 7

  # DynamoDB Table for Quotes
  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dcc-quotes-optimized
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
        - AttributeName: GSI3PK
          AttributeType: S
        - AttributeName: GSI3SK
          AttributeType: S
        - AttributeName: GSI4PK
          AttributeType: S
        - AttributeName: GSI4SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI3
          KeySchema:
            - AttributeName: GSI3PK
              KeyType: HASH
            - AttributeName: GSI3SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI4
          KeySchema:
            - AttributeName: GSI4PK
              KeyType: HASH
            - AttributeName: GSI4SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # DynamoDB Table for Daily Nuggets Subscriptions
  DailyNuggetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dcc-daily-nuggets-subscriptions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: timezone
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: timezone-index
          KeySchema:
            - AttributeName: timezone
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # DynamoDB Table for Notification Analytics
  NotificationAnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dcc-notification-analytics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: notification_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: notification_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # SQS Queue for Image Generation
  ImageGenerationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dcc-image-generation-queue
      VisibilityTimeoutSeconds: 300
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 20

Outputs:
  QuoteImagesBucketName:
    Description: "S3 Bucket for quote images"
    Value: !Ref QuoteImagesBucket
    Export:
      Name: !Sub "${AWS::StackName}-QuoteImagesBucket"
      
  QuoteImagesBucketArn:
    Description: "S3 Bucket ARN for quote images"
    Value: !GetAtt QuoteImagesBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-QuoteImagesBucketArn"
      
  ExportsBucketName:
    Description: "S3 Bucket for exports"
    Value: !Ref ExportsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ExportsBucket"
      
  QuotesTableName:
    Description: "DynamoDB table for quotes"
    Value: !Ref QuotesTable
    Export:
      Name: !Sub "${AWS::StackName}-QuotesTable"
      
  DailyNuggetsTableName:
    Description: "DynamoDB table for daily nuggets subscriptions"
    Value: !Ref DailyNuggetsTable
    Export:
      Name: !Sub "${AWS::StackName}-DailyNuggetsTable"
      
  ImageGenerationQueueUrl:
    Description: "SQS Queue URL for image generation"
    Value: !Ref ImageGenerationQueue
    Export:
      Name: !Sub "${AWS::StackName}-ImageGenerationQueue"
      
  ImageGenerationQueueArn:
    Description: "SQS Queue ARN for image generation"
    Value: !GetAtt ImageGenerationQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ImageGenerationQueueArn"